1. Install TensorFlow and Keras in your Python environment, then write a script to create a simple 2-layer neural network (input, hidden, output) using Keras' Sequential API.

In [8]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
model = Sequential([
    Dense(4,activation= "relu", input_shape=(3,)),
    Dense(1, activation="sigmoid")
])

c:\Users\hp\.conda\envs\tfenv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [4]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21 (84.00 B)

 Trainable params: 21 (84.00 B)

 Non-trainable params: 0 (0.00 B)

2. Given a simple neural network with one hidden layer (using Keras), print out the weights before and after one training step on dummy data to observe how the weight update rule works.

In [5]:
model = Sequential([
    Dense(4, activation='relu', input_shape=(2,)),
    Dense(1,activation='sigmoid')
])

c:\Users\hp\.conda\envs\tfenv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.compile(optimizer='sgd',loss='binary_crossentropy')

In [9]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype=float)

y = np.array([0, 1, 1, 0], dtype=float)

In [10]:
print("Weights Before Training:\n")
for i, layer in enumerate(model.layers):
    print(f"Layer {i+1}")
    weights, bias = layer.get_weights()
    print("Weights:\n", weights)
    print("Bias:\n", bias)
    print()

Weights Before Training:

Layer 1
Weights:
 [[ 0.70413804  0.74679685  0.06367302  0.42972112]
 [-0.4525578   0.82213736  0.6956699  -0.5948663 ]]
Bias:
 [0. 0. 0. 0.]

Layer 2
Weights:
 [[ 0.93314123]
 [-0.778447  ]
 [-0.64246464]
 [ 0.8405533 ]]
Bias:
 [0.]



In [12]:
model.fit(X,y, epochs = 1 , batch_size = 4, verbose = 0)

In [13]:
print("\nWeights After One Training Step:\n")
for i, layer in enumerate(model.layers):
    print(f"Layer {i+1}")
    weights, bias = layer.get_weights()
    print("Weights:\n", weights)
    print("Bias:\n", bias)
    print()


Weights After One Training Step:

Layer 1
Weights:
 [[ 0.70464194  0.7463765   0.06332609  0.43056643]
 [-0.45299235  0.82104456  0.69476795 -0.5948663 ]]
Bias:
 [ 0.00050389 -0.00187567 -0.00154802  0.00084532]

Layer 2
Weights:
 [[ 0.9337322 ]
 [-0.77688956]
 [-0.6414536 ]
 [ 0.8409854 ]]
Bias:
 [0.00115951]



3. Manually calculate the gradient of the loss with respect to the weights for a single neuron using the chain rule, given these values: input x=2, weight w=0.5, bias b=1, activation=sigmoid, target y=1.<br><br><em><strong>Hint:</strong> Write out each step of the derivative using the chain rule, then compute the numeric value.</em>

In [1]:
import math

In [2]:
x = 2
w = 0.5
b = 1
y = 1

In [3]:
z = w * x + b
a = 1/(1+math.exp(-z))

In [4]:
loss = 0.5 * (a-y)**2

In [5]:
dL_da = a - y
da_dz = a * (1 - a)
dz_dw = x
gradient = dL_da * da_dz * dz_dw

In [6]:
print("Weighted Sum (z):", z)
print("Sigmoid Output (a):", round(a, 4))
print("Loss:", round(loss, 4))
print("dL/da:", round(dL_da, 4))
print("da/dz:", round(da_dz, 4))
print("dz/dw:", dz_dw)
print("Gradient (dL/dw):", round(gradient, 4))

Weighted Sum (z): 2.0
Sigmoid Output (a): 0.8808
Loss: 0.0071
dL/da: -0.1192
da/dz: 0.105
dz/dw: 2
Gradient (dL/dw): -0.025


4. Build a function in Python that simulates vanishing gradient by applying the sigmoid activation repeatedly to an input (e.g., 0.9) for 10 layers, and print the final output.
<br><br><em><strong>Hint:</strong> Observe how the value shrinks as you increase the number of layers.</em>

In [7]:
import math

In [8]:
def sigmoid(x):
    return 1 / (1+math.exp(-x))

In [9]:
def vanishing_gradient(input_value , layers):
    value = input_value

    print("Layer\tOutput")
    for i in range(1,layers+1):
        value = sigmoid(value)
        print(f"{i}\t{value:.6f}")    
    return value

In [10]:
input_value = 0.9

In [12]:
final_output = vanishing_gradient(input_value, 10)

Layer	Output
1	0.710950
2	0.670611
3	0.661640
4	0.659629
5	0.659177
6	0.659075
7	0.659053
8	0.659048
9	0.659046
10	0.659046


In [13]:
print("\nFinal Output after 10 layers:", final_output)


Final Output after 10 layers: 0.6590461433964991


5. Use ChatGPT or Copilot to generate Python code that demonstrates exploding gradients in a deep network by initializing weights with large values, then explain in 2-3 lines what happens to the gradients during backpropagation.

In [14]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Large weight initialization
weights = [10, 10, 10, 10, 10]

# Input
x = 1.0

print("Layer\tOutput")

# Forward pass through 5 layers
for i, w in enumerate(weights, start=1):
    x = sigmoid(w * x)
    print(f"{i}\t{x:.6f}")

# Simulated gradient during backpropagation
gradient = 1.0

print("\nBackpropagation Gradients:")

for i, w in enumerate(reversed(weights), start=1):
    gradient = gradient * w
    print(f"Layer {len(weights)-i+1}: {gradient:.2f}")

Layer	Output
1	0.999955
2	0.999955
3	0.999955
4	0.999955
5	0.999955

Backpropagation Gradients:
Layer 5: 10.00
Layer 4: 100.00
Layer 3: 1000.00
Layer 2: 10000.00
Layer 1: 100000.00


Large weight values cause the gradients to grow rapidly during backpropagation. As the gradient is multiplied by these large weights across many layers, it can become extremely large (explode), leading to unstable training, very large weight updates, and possible divergence of the model.