1. Create a 6x6 NumPy array with random integers (0-255) to simulate a grayscale image, then apply a 2x2 max pooling operation with a stride of 2 and print the resulting reduced array.

In [3]:
import numpy as np

In [4]:
np.random.seed(42)
image = np.random.randint(0, 256, (6, 6))

In [5]:
print("Original 6x6 Image:")
print(image)

Original 6x6 Image:
[[102 179  92  14 106  71]
 [188  20 102 121 210 214]
 [ 74 202  87 116  99 103]
 [151 130 149  52   1  87]
 [235 157  37 129 191 187]
 [ 20 160 203  57  21 252]]


In [6]:
def max_pooling(image):
    rows, cols = image.shape

    output = np.zeros((rows // 2, cols // 2), dtype=int)

    for i in range(0, rows, 2):
        for j in range(0, cols, 2):
            window = image[i:i+2, j:j+2]
            output[i // 2, j // 2] = np.max(window)

    return output

In [7]:
pooled_image = max_pooling(image)

In [8]:
print("\nPooled Image (2x2 Max Pooling, Stride = 2):")
print(pooled_image)


Pooled Image (2x2 Max Pooling, Stride = 2):
[[188 121 214]
 [202 149 103]
 [235 203 252]]


2. Write a Python function average_pooling_2x2(image) that takes a 2D NumPy array and returns a new array after applying 2x2 average pooling with stride 2.

In [9]:
def average_pooling_2x2(image):
    rows, cols = image.shape

    output = np.zeros((rows // 2, cols // 2), dtype=float)

    for i in range(0, rows, 2):
        for j in range(0, cols, 2):
            window = image[i:i+2, j:j+2]
            output[i // 2, j // 2] = np.mean(window)

    return output

In [10]:
image = np.array([
    [10, 20, 30, 40, 50, 60],
    [15, 25, 35, 45, 55, 65],
    [70, 80, 90, 100, 110, 120],
    [75, 85, 95, 105, 115, 125],
    [130, 140, 150, 160, 170, 180],
    [135, 145, 155, 165, 175, 185]
])

In [11]:
pooled_image = average_pooling_2x2(image)

In [12]:
print("Original Image:")
print(image)

print("\nAverage Pooled Image:")
print(pooled_image)

Original Image:
[[ 10  20  30  40  50  60]
 [ 15  25  35  45  55  65]
 [ 70  80  90 100 110 120]
 [ 75  85  95 105 115 125]
 [130 140 150 160 170 180]
 [135 145 155 165 175 185]]

Average Pooled Image:
[[ 17.5  37.5  57.5]
 [ 77.5  97.5 117.5]
 [137.5 157.5 177.5]]


3. Given a 4x4 feature map array, manually perform both max pooling and average pooling with a 2x2 window and stride 2, and compare the results side by side.<br><br><em><strong>Hint:</strong> Show both resulting arrays and explain in one line which pooling method keeps more details from the original image.</em>

In [13]:
feature_map = np.array([
    [1, 3, 2, 4],
    [5, 6, 1, 2],
    [7, 2, 8, 3],
    [4, 9, 5, 6]
])

max_pool = np.zeros((2, 2), dtype=int)
avg_pool = np.zeros((2, 2), dtype=float)

In [14]:
for i in range(0, 4, 2):
    for j in range(0, 4, 2):
        window = feature_map[i:i+2, j:j+2]

        max_pool[i // 2, j // 2] = np.max(window)
        avg_pool[i // 2, j // 2] = np.mean(window)

In [15]:
print("Original Feature Map:")
print(feature_map)

print("\nMax Pooling Output:")
print(max_pool)

print("\nAverage Pooling Output:")
print(avg_pool)

Original Feature Map:
[[1 3 2 4]
 [5 6 1 2]
 [7 2 8 3]
 [4 9 5 6]]

Max Pooling Output:
[[6 4]
 [9 8]]

Average Pooling Output:
[[3.75 2.25]
 [5.5  5.5 ]]


4. Combine a single 3x3 convolution layer (use any simple filter, e.g., edge detection) followed by a 2x2 max pooling layer on a 5x5 input array. Show the output after each step.

In [16]:
def convolution(image, kernel):
    image_rows, image_cols = image.shape
    kernel_rows, kernel_cols = kernel.shape

    output_rows = image_rows - kernel_rows + 1
    output_cols = image_cols - kernel_cols + 1

    output = np.zeros((output_rows, output_cols))

    for i in range(output_rows):
        for j in range(output_cols):
            region = image[i:i+kernel_rows, j:j+kernel_cols]
            output[i, j] = np.sum(region * kernel)

    return output

In [21]:
def max_pooling(feature_map):
    rows, cols = feature_map.shape

    output_rows = rows // 2
    output_cols = cols // 2

    output = np.zeros((output_rows, output_cols))
    for i in range(0, rows - 1, 2):
        for j in range(0, cols - 1, 2):
            window = feature_map[i:i+2, j:j+2]
            output[i // 2, j // 2] = np.max(window)

    return output

In [22]:
input_image = np.array([
    [1, 2, 3, 0, 1],
    [4, 5, 6, 1, 2],
    [7, 8, 9, 2, 3],
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 0]
])

kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

In [23]:
conv_output = convolution(input_image, kernel)
pool_output = max_pooling(conv_output)

In [24]:
print("Input Image:")
print(input_image)

print("\nAfter Convolution:")
print(conv_output)

print("\nAfter 2x2 Max Pooling:")
print(pool_output)

Input Image:
[[1 2 3 0 1]
 [4 5 6 1 2]
 [7 8 9 2 3]
 [1 2 3 4 5]
 [6 7 8 9 0]]

After Convolution:
[[-6. 12. 12.]
 [-6.  8.  8.]
 [-6.  2. 12.]]

After 2x2 Max Pooling:
[[12.]]


5. Explain in your own words, using an example from Instagram or Zomato, how pooling layers help reduce computation and improve feature extraction in deep learning models.

##### Pooling Layers in Deep Learning

**Example: Instagram**

When Instagram analyzes a photo, the important features (such as a person's face or an object) may appear in different positions or sizes. A pooling layer reduces the size of the feature maps by keeping only the most important information, which decreases the amount of computation and memory required. This allows the model to recognize faces or objects more efficiently while ignoring small, unimportant details.

**Example: Zomato**

When users upload food photos, pooling helps the CNN focus on important features like the shape, texture, and edges of the food while reducing unnecessary background details. This makes food recognition faster and more accurate, improving the app's ability to identify dishes and recommend similar items.