1. Create a 5x5 NumPy matrix with random integers from 0 to 9, then define a 3x3 filter (kernel) and manually perform a single convolution operation (no padding, stride 1) to produce the activation map.

In [1]:
import numpy as np

In [2]:
np.random.seed(42)  # For reproducible results
image = np.random.randint(0, 10, (5, 5))


In [3]:
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

In [4]:
output_rows = image.shape[0] - kernel.shape[0] + 1
output_cols = image.shape[1] - kernel.shape[1] + 1

In [5]:
activation_map = np.zeros((output_rows, output_cols))

In [6]:
for i in range(output_rows):
    for j in range(output_cols):
        region = image[i:i+3, j:j+3]
        activation_map[i, j] = np.sum(region * kernel)

In [7]:
print("Input Image:")
print(image)

print("\nKernel:")
print(kernel)

print("\nActivation Map:")
print(activation_map)

Input Image:
[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]
 [4 0 9 5 8]]

Kernel:
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

Activation Map:
[[ -2.  -1.   5.]
 [ -4.  -4.  10.]
 [-12.  -4.   9.]]


In [8]:
def apply_stride_convolution(input_matrix, kernel, stride):
    input_rows, input_cols = input_matrix.shape
    kernel_rows, kernel_cols = kernel.shape

    output_rows = ((input_rows - kernel_rows) // stride) + 1
    output_cols = ((input_cols - kernel_cols) // stride) + 1

    activation_map = np.zeros((output_rows, output_cols))

    out_i = 0
    for i in range(0, input_rows - kernel_rows + 1, stride):
        out_j = 0
        for j in range(0, input_cols - kernel_cols + 1, stride):
            region = input_matrix[i:i+kernel_rows, j:j+kernel_cols]
            activation_map[out_i, out_j] = np.sum(region * kernel)
            out_j += 1
        out_i += 1

    return activation_map

In [9]:
input_matrix = np.array([
    [1, 2, 3, 0, 1, 2],
    [4, 5, 6, 1, 2, 3],
    [7, 8, 9, 2, 3, 4],
    [1, 2, 3, 4, 5, 6],
    [6, 7, 8, 9, 0, 1],
    [2, 3, 4, 5, 6, 7]
])

kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

stride = 2

In [10]:
activation_map = apply_stride_convolution(input_matrix, kernel, stride)

In [11]:
print("Input Matrix:")
print(input_matrix)

print("\nKernel:")
print(kernel)

print("\nStride:", stride)

print("\nActivation Map:")
print(activation_map)

Input Matrix:
[[1 2 3 0 1 2]
 [4 5 6 1 2 3]
 [7 8 9 2 3 4]
 [1 2 3 4 5 6]
 [6 7 8 9 0 1]
 [2 3 4 5 6 7]]

Kernel:
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

Stride: 2

Activation Map:
[[-6. 12.]
 [-6. 12.]]


3. Modify your convolution code to add zero-padding of 1 around the input matrix before applying the convolution, and show the new activation map output.

In [12]:
def convolution_with_padding(input_matrix, kernel, padding=1):
    padded_matrix = np.pad(
        input_matrix,
        pad_width=padding,
        mode='constant',
        constant_values=0
    )

    input_rows, input_cols = padded_matrix.shape
    kernel_rows, kernel_cols = kernel.shape

    output_rows = input_rows - kernel_rows + 1
    output_cols = input_cols - kernel_cols + 1

    activation_map = np.zeros((output_rows, output_cols))

    for i in range(output_rows):
        for j in range(output_cols):
            region = padded_matrix[i:i+kernel_rows, j:j+kernel_cols]
            activation_map[i, j] = np.sum(region * kernel)

    return padded_matrix, activation_map

In [14]:
input_matrix = np.array([
    [1, 2, 3, 0, 1],
    [4, 5, 6, 1, 2],
    [7, 8, 9, 2, 3],
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 0]
])

# 3x3 kernel
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

In [16]:
padded_matrix, activation_map = convolution_with_padding(
    input_matrix,
    kernel,
    padding=1
)

In [17]:
print("Original Input Matrix:")
print(input_matrix)

print("\nPadded Input Matrix:")
print(padded_matrix)

print("\nKernel:")
print(kernel)

print("\nActivation Map:")
print(activation_map)

Original Input Matrix:
[[1 2 3 0 1]
 [4 5 6 1 2]
 [7 8 9 2 3]
 [1 2 3 4 5]
 [6 7 8 9 0]]

Padded Input Matrix:
[[0 0 0 0 0 0 0]
 [0 1 2 3 0 1 0]
 [0 4 5 6 1 2 0]
 [0 7 8 9 2 3 0]
 [0 1 2 3 4 5 0]
 [0 6 7 8 9 0 0]
 [0 0 0 0 0 0 0]]

Kernel:
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

Activation Map:
[[ -7.  -4.   6.   6.   1.]
 [-15.  -6.  12.  12.   3.]
 [-15.  -6.   8.   8.   7.]
 [-17.  -6.   2.  12.  15.]
 [ -9.  -4.  -4.   6.  13.]]


4. Visualize the effect of different filters by applying both an edge detection kernel and a blur kernel to the same 5x5 matrix and print both activation maps side by side.<br><br><em><strong>Hint:</strong> Use the Sobel or Laplacian kernel for edge detection and an averaging kernel for blur.</em>


In [18]:
def convolution(input_matrix, kernel):
    input_rows, input_cols = input_matrix.shape
    kernel_rows, kernel_cols = kernel.shape

    output_rows = input_rows - kernel_rows + 1
    output_cols = input_cols - kernel_cols + 1

    activation_map = np.zeros((output_rows, output_cols))

    for i in range(output_rows):
        for j in range(output_cols):
            region = input_matrix[i:i+kernel_rows, j:j+kernel_cols]
            activation_map[i, j] = np.sum(region * kernel)

    return activation_map


In [19]:
input_matrix = np.array([
    [1, 2, 3, 0, 1],
    [4, 5, 6, 1, 2],
    [7, 8, 9, 2, 3],
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 0]
])

edge_kernel = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
])


In [20]:
blur_kernel = np.array([
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9]
])


In [21]:
edge_output = convolution(input_matrix, edge_kernel)
blur_output = convolution(input_matrix, blur_kernel)

In [22]:
print("Input Matrix:")
print(input_matrix)

print("\nEdge Detection Activation Map:")
print(edge_output)

print("\nBlur Activation Map:")
print(blur_output)

Input Matrix:
[[1 2 3 0 1]
 [4 5 6 1 2]
 [7 8 9 2 3]
 [1 2 3 4 5]
 [6 7 8 9 0]]

Edge Detection Activation Map:
[[  8. -16. -16.]
 [  8. -14. -14.]
 [  8.   0. -10.]]

Blur Activation Map:
[[5.         4.         3.        ]
 [5.         4.44444444 3.88888889]
 [5.66666667 5.77777778 4.77777778]]


5. Pick any Instagram photo, convert it to grayscale and a small NumPy array (e.g., 8x8), and use your convolution function to apply a custom filter of your choice. Show the input and output arrays and briefly describe what feature your filter detects.

In [23]:
import numpy as np
from PIL import Image

In [24]:
def convolution(image, kernel):
    image_rows, image_cols = image.shape
    kernel_rows, kernel_cols = kernel.shape

    output_rows = image_rows - kernel_rows + 1
    output_cols = image_cols - kernel_cols + 1

    output = np.zeros((output_rows, output_cols))

    for i in range(output_rows):
        for j in range(output_cols):
            region = image[i:i+kernel_rows, j:j+kernel_cols]
            output[i, j] = np.sum(region * kernel)

    return output

In [30]:
image = Image.open(r"E:\TOPS-DS\instagram_photo.jpeg")
image = image.convert("L")
image = image.resize((8, 8))
image_array = np.array(image)

In [31]:
kernel = np.array([
    [-1, -1, -1],
    [ 0,  0,  0],
    [ 1,  1,  1]
])

In [32]:
output_array = convolution(image_array, kernel)

In [33]:
print("Input 8x8 Grayscale Image:")
print(image_array)

print("\nOutput Feature Map:")
print(output_array)

Input 8x8 Grayscale Image:
[[  0  30 107  96  72  84  32   0]
 [ 27 124  78  16  16  37 107  27]
 [106 109   8  12  80  68  73 101]
 [134  87  19  74 120  67  42 131]
 [134  79  11  77  89  65  69 135]
 [ 90  31   9  32   7  64  90  75]
 [ 19  14  10  15   9  17  18   8]
 [  2   3   8   7   9   5   2   3]]

Output Feature Map:
[[  86. -104. -175.  -92.   33.  126.]
 [  11.  -38.  103.  192.   69.   69.]
 [   1.   38.   77.   71.    2.   27.]
 [-110. -108. -165. -158.  -68.  -11.]
 [-181. -128. -143. -190. -179. -226.]
 [-117.  -54.  -24.  -82. -145. -219.]]
