1. Create a simple Python function called neuron_output that takes three arguments: input_value, weight, and bias, and returns the output using the formula output = input_value * weight + bias.

In [2]:
def neuron_output(input_value,weight,bias):
    output = input_value * weight + bias
    return output 

In [3]:
input_value = 5
weight = 0.8
bias = 3

In [4]:
output = neuron_output(input_value,weight,bias)

In [5]:
print("The output of the neuron is :",output)

The output of the neuron is : 7.0


2. Given an array of input values representing the number of likes on 5 Instagram posts, apply a weight of 0.8 and a bias of 2 to each input using your neuron_output function, and print the resulting outputs. <br><br><em><strong>Hint:</strong> Use a for loop to process each input value.</em>

In [6]:
likes=[100, 500 ,280 , 320 , 589]

In [7]:
weight = 0.8
bias = 2

In [8]:
for likes_count in likes:
    output = neuron_output(likes_count , weight,bias)
    print("Input:",likes_count, "Output:", output)

Input: 100 Output: 82.0
Input: 500 Output: 402.0
Input: 280 Output: 226.0
Input: 320 Output: 258.0
Input: 589 Output: 473.20000000000005


3. Write Python code to initialize a list of 10 neuron weights using three different strategies: all zeros, random values between -1 and 1, and Xavier initialization (drawn from a normal distribution with mean 0 and standard deviation 1/sqrt(n), where n=10). Print the three lists for comparison <br><br><em><strong> Hint:</strong> Use the numpy library for random and normal distributions.</em>

In [9]:
import numpy as np

In [10]:
n = 10

In [ ]:
weights_zeros = np.zeros(n)
weights_random = np.random.rand(n)
sd = 1 / np.sqrt(n)
weights_xavier = np.random.normal(0,sd,n)

In [13]:
print("Zero initialization:")
print(weights_zeros)

Zero initialization:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
print("Random Initialization:")
weights_random

Random Initialization:


array([0.19120761, 0.69571765, 0.23729379, 0.90646209, 0.54821285,
       0.40161325, 0.04528537, 0.71115857, 0.41302458, 0.264553  ])

In [15]:
print("Xavier Initialization:")
weights_xavier

Xavier Initialization:


array([-0.0392895 ,  0.63875703, -0.20289722, -0.08439666, -0.10432485,
       -0.02950801,  0.35417347, -0.07396868,  0.34556183,  0.30786726])

4. Demonstrate with code why having a bias term is essential: set up a neuron with weight=0.5 and bias=0, and another with weight=0.5 and bias=5. For an input of 0, show the outputs for both cases and explain the difference in a comment.

In [16]:
input_value = 0
weight = 0.5
bias1 = 0
bias2 = 5 

In [18]:
output1 = neuron_output(input_value,weight,bias1 )
output2 = neuron_output(input_value,weight,bias2)

In [20]:
print("Case 1: bias = 0")
output1

Case 1: bias = 0


0.0

In [21]:
print("Case 2: bias =0.5")
output2

Case 2: bias =0.5


5.0

#### Explanation:
With input = 0:
Output = (0 × 0.5) + 0 = 0
Output = (0 × 0.5) + 5 = 5
The bias allows the neuron to produce a non-zero output even when the input is zero.
Without a bias, the output would always be zero for a zero input, reducing the neuron's flexibility.

5. Modify the neuron_output function to accept a list of input values and a corresponding list of weights, plus a single bias. Compute the weighted sum plus bias for a Spotify playlist (inputs: [2, 4, 1], weights: [0.6, 0.3, 0.1], bias: 1) and print the result.<br><br><em><strong>Constraint:</strong> Do not use any external libraries except basic Python (no numpy).</em>

In [24]:
def neuron_output(inputs, weights , bias):
    weighted_sum = 0

    for i in range(len(inputs)):
        weighted_sum+= inputs[i]* weights[i]

    output =weighted_sum +bias 
    return output

In [25]:
inputs = [2,3,6]
weights = [0.3,0.6,1]
bias = 1

In [26]:
result = neuron_output(inputs , weights , bias)

In [27]:
print("Inputs:", inputs)
print("Weights:",weights)
print("Bias:", bias)
print("Output:",result)

Inputs: [2, 3, 6]
Weights: [0.3, 0.6, 1]
Bias: 1
Output: 9.4
